sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.6.2

before_install:
  - docker-compose build
  - docker-compose up -d

install:
  - npm install -g newman

script:
  - newman run tests/ci_metrics_api.postman_collection.json
